# https://docs.docker.com/compose/compose-file/

# https://github.com/docker/awesome-compose
services:
  app:
    container_name: app
    build:
      context: .
      target: final
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      mongo:
        condition: service_started

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env