# https://docs.docker.com/compose/compose-file/

# https://github.com/docker/awesome-compose
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env

  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - ./typesense/typesense-data:/data
