# https://docs.docker.com/compose/compose-file/

# https://github.com/docker/awesome-compose
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env